@extends('layouts.guest')

@section('title', 'Naudojimosi taisyklės')

@section('content')
    <div class="container py-[50px]">
        <h1 class="mb-8 text-center text-3xl font-bold">Naudojimosi taisyklės</h1>

        <h2 class="my-8 text-xl font-bold">1. TAISYKLIŲ TAIKYMAS IR AIŠKINIMAS</h2>
        <p>1.1. Šis dokumentas yra sutartis tarp Tautvydas Mickonis (Individualios veiklos pažymos nr. 911930, el. pašto adresas – info@BALDUGAMYBA.LT, tel. nr.: +37069221168) (toliau – BALDUGAMYBA.LT) ir Jūsų (toliau – Klientas arba Jūs) dėl naudojimosi interneto svetaine www.BALDUGAMYBA.LT“ (toliau – Svetainė).</p>
        <p>1.2. Naudodamiesi Svetaine Jūs patvirtinate, kad esate susipažinęs su šios sutarties sąlygomis ir taisyklėmis (toliau – Taisyklės), sutinkate su Taisyklėmis ir įsipareigojate jų laikytis.</p>
        <p>1.3. Naudojimasis Svetaine šių Taisyklių prasme apima visų ir bet kokių veiksmų atlikimą, Klientui prisijungus prie Svetainės naudojantis interneto ryšiu. Šių Taisyklių prasme, paslaugos apima visus ir bet kokius Kliento veiksmus, kuriuos jis gali atlikti Svetainėje, įskaitant skelbimų skelbimą, skelbiamos informacijos skaitymą, klausimų, atsiliepimų ir komentarų rašymą, tiesioginių (online) žinučių rašymą, bet kokio pobūdžio informacijos ir (ar) duomenų pateikimą, siuntimą bei gavimą, tačiau tuo neapsiribojant (toliau – Paslaugos). Klientas bet kokiu būdu ir forma naudodamasis Svetaine ir (ar) Paslaugomis, besąlygiškai ir neatšaukiamai įsipareigoja laikytis visų šiose Taisyklėse nustatytų reikalavimų. Jei Klientas nesutinka besąlygiškai bei neatšaukiamai prisiimti ir laikytis visų šiose Taisyklėse nustatytų įsipareigojimų, jis neturi teisės naudotis jokiomis Paslaugomis ir (ar) Svetaine.</p>
        <p>1.4. Dalis Svetainėje teikiamų Paslaugų yra teikiamos Klientui už atlygį (toliau – Mokamos Paslaugos). Mokamos Paslaugos yra apibūdintos ir nurodytos Svetainėje, Jų kaina nurodyta konkrečios Mokamos Paslaugos užsakymo puslapyje. Toliau šiose Taisyklėse nuoroda į „Paslaugas“ apims visas Paslaugas, įskaitant ir Mokamas Paslaugas, o nuoroda į „Mokamas Paslaugas“ apims tik tas Paslaugas už kurias Klientas moka užmokestį.</p>
        <p>1.5. Visi Klientai yra skirstomi į verslo ir privačius klientus ir apibrėžiami kaip nurodyta žemiau:</p>
        <p>1.5.1. Verslo Klientams priskiriami fiziniai ir juridiniai asmenys, kurie, atsižvelgiant į įkeltų skelbimų kiekį, skelbimų turinį (pavyzdžiui, aprašymo, nuotraukų), kitas turimas susijusias paskyras, Paslaugomis naudojasi prekybos, verslo, amato, profesijos tikslais (pavyzdžiui, vykdo tęstinę prekybą, teikia paslaugas, parduoda veislinių gyvūnų jauniklius, vykdo ūkinę veiklą, superka daiktus ir pan.) (toliau – Verslininkai);</p>
        <p>1.5.2. Privatiems Klientams priskiriami fiziniai ir juridiniai asmenys, kurie Paslaugomis naudojasi su savo verslu, amatu ar profesija nesusijusiais tikslais (vartojimo tikslais) (toliau – Privatūs klientai).</p>
        <p>1.6. Be šių Taisyklių santykiams tarp Kliento ir BALDUGAMYBA.LT reguliuoti taikomos Lietuvos Respublikos teisės aktų nuostatos, specialios sąlygos ir taisyklės, pateikiamos Svetainėje bei nusistovėjusi gera verslo praktika. Vartotojų apsaugos reikalavimai netaikomi sutarčiai, kai prekes, paslaugas siūlantis asmuo nėra Verslininkas.</p>
        <p>1.7. Jeigu kuri nors šių Taisyklių nuostata prieštarauja įstatymams arba dėl kokios nors priežasties tampa dalinai arba visai negaliojančia, ji nedaro negaliojančiomis likusių Taisyklių nuostatų.</p>

        <h2 class="my-8 text-xl font-bold">2. BENDROSIOS SĄLYGOS</h2>
        <p>2.1. BALDUGAMYBA.LT suteikia Klientams virtualią erdvę, t. y. Svetainę, kurioje Klientai turi galimybę paskelbti savo skelbimus apie siūlomas ar ieškomas prekes ar paslaugas (toliau – Skelbimai), skaityti Skelbimus, ieškoti Skelbimų, rašyti po Skelbimais komentarus ir tiesiogines žinutes bei naudotis kitomis Paslaugomis.</p>
        <p>2.2. Klientų keliami Skelbimai Svetainėje yra aiškiai atskirti: Privačių klientų Skelbimai yra pažymėti „Privataus asmens skelbimas“ kontaktų skiltyje, o Verslininkų skelbimai yra pažymėti „Verslo kliento skelbimas“.</p>
        <p>2.3. Klientas pripažįsta ir sutinka, kad jis pats, o ne BALDUGAMYBA.LT, yra atsakingas už visą Turinį, kurį gauna, siunčia ar bet kuriais kitais būdais perduoda naudodamasis Svetaine ir (ar) Paslaugomis. Turinys šiose Taisyklėse reiškia Skelbimą, o taip pat visą ir bet kokią informaciją, įskaitant duomenis, duomenų bazes, simbolius, tekstą, fotografijas, paveikslėlius, video medžiagą, dokumentus, komentarus, žinutes, bet tuo neapsiribojant, kurią Klientas pateikia, gauna, saugo, siunčia, priima ar perduoda naudodamasis Paslaugomis ir (ar) Svetaine (toliau – Turinys).</p>
        <p>2.4. Klientas supranta ir sutinka su tuo, jog BALDUGAMYBA.LT nekontroliuoja kitų Svetainės naudotojų, lankytojų ar trečiųjų šalių Turinio, kurį Klientas gali gauti, perskaityti ar kitaip sužinoti naudodamasis Svetaine ar Paslaugomis, todėl BALDUGAMYBA.LT nebus atsakingas dėl tokio Turinio tikslumo, vientisumo ir (ar) kokybės.</p>
        <p>2.5. Klientas supranta ir sutinka su tuo, kad BALDUGAMYBA.LT turi teisę, tačiau ne pareigą, savo nuožiūra tikrinti Kliento gaunamą ir perduodamą Turinį, siekiant aptikti BALDUGAMYBA.LT nepageidaujamu ar pažeidžiančiu šias Taisykles pripažįstamą Turinį, o tokį Turinį aptikus – jį šalinti ar blokuoti tokio Turinio bet kokį perdavimą.</p>
        <p>2.6. BALDUGAMYBA.LT jokiu būdu nedalyvaus pirkimo-pardavimo ar kitokiuose su Svetainėje siūlomomis prekėmis ir (ar) paslaugomis ar Skelbimais susijusiuose sandoriuose tarp Klientų (nei kaip tarpininkas, įgaliotas asmuo, atstovas ar kaip kitaip). BALDUGAMYBA.LT nebus Kliento agentu, atstovu, tarpininku ir kt.</p>
        <p>2.7. Bet koks informacijos paskelbimas ir (ar) padarymas viešai prieinama Svetainėje nėra laikoma BALDUGAMYBA.LT pasiūlymu (oferta) sudaryti sandorį.</p>
        <p>2.8. Kliento sudaryta Sutartis dėl Skelbimo patalpinimo Svetainėje yra terminuota, priklausomai nuo Skelbimo kategorijos: Skelbimai daugumoje kategorijų galioja 60 dienų (drabužių / avalynės kategorijoje - 90 dienų, ilgalaikės namų, butų ir kambarių nuomos kategorijose - 40 dienų, kolekcionavimo ir dovanojimo kategorijose - 30 dienų). Anksčiau nutraukti sutartį Klientas gali savo iniciatyva ištrindamas Skelbimą, tačiau pinigai už neišnaudotą Skelbimo talpinimo laiką nebus grąžinami. Daugiau informacijos skaitykite Taisyklių 6.6. punkte.</p>
        <p>2.9. Visi pranešimai ir informacija tarp Kliento ir BALDUGAMYBA.LT bus siunčiama elektroninėmis priemonėmis adresais, nurodytais šiose Taisyklėse arba Svetainėje, nebent šiose Taisyklėse nurodyta kitaip.</p>

        <h2 class="my-8 text-xl font-bold">3. INTELEKTINĖS NUOSAVYBĖS TEISĖS</h2>
        <p>3.1. Visos intelektinės nuosavybės teisės į Svetainę ir visą jos turinį ir duomenų bazę, įskaitant autorių teises, pramoninės intelektinės nuosavybės teises, firmų vardus, know-how, komercines ir gamybines paslaptis, priklauso BALDUGAMYBA.LT arba BALDUGAMYBA.LT teisėtai naudojasi trečiųjų asmenų suteiktomis teisėmis.</p>
        <p>3.2. Visos teisės į Svetainę ir joje esančius kūrinius yra saugomos. Joks Svetainėje esantis Turinys ar kitokia informacija negali būti atgaminamas, padaromas viešai prieinamu arba platinamas be išankstinio raštiško BALDUGAMYBA.LT sutikimo.</p>
        <p>3.3. Visi prekių ženklai, kurie pateikiami Svetainėje, yra BALDUGAMYBA.LT arba BALDUGAMYBA.LT juos teisėtai naudoja, išskyrus tuos prekių ženklus, kuriuos įkėlė Svetainės naudotojai.</p>
        <p>3.4. Naudodamasis Svetaine ar Paslaugomis ir teikdamas, įvesdamas ar kitaip siųsdamas Turinį Klientas neatlygintinai, neribotam laikui, neribotoje teritorijoje ir maksimalia įstatymų leidžiama apimtimi suteikia BALDUGAMYBA.LT visas turtines autorių teises, reikalingas BALDUGAMYBA.LT iš šių Taisyklių kylančioms teisėms įgyvendinti ir pareigoms vykdyti šias teises, įskaitant, tačiau neapsiribojant:</p>
        <p>3.4.1. teisę bet kokia forma ar būdu atgaminti, keisti, versti, viešai skelbti ir padaryti viešai prieinamu ir platinti parduodant, nuomojant, teikiant panaudai ar kitaip perduodant nuosavybėn arba valdyti Kliento pateiktą Turinį;</p>
        <p>3.4.2. teisę kurti išvestinius kūrinius iš Kliento pateikto Turinio.</p>
        <p>3.5. Šalys susitaria, kad kiekvieną kartą pateikdamas bet kokį Turinį Klientas patvirtina ir garantuoja BALDUGAMYBA.LT, kad jis turi visas teises, leidimus, sutikimus ir ar licencijas atlikti tuos veiksmus su Turiniu, kuriuos Klientas atlieka, įskaitant teisę naudoti Turinyje esančius prekių ženklus ir autorių teisių objektus, skelbti Turinį, padaryti jį viešai prieinamą.</p>

        <h2 class="my-8 text-xl font-bold">4. REIKALAVIMAI SKELBIMŲ TURINIUI, FORMAI BEI KITOS NAUDOJIMOSI BALDUGAMYBA.LT SĄLYGOS</h2>
        <p>4.1. Klientas įsipareigoja:</p>
        <p>4.1.1. naudodamasis Svetaine ir (ar) Paslaugomis paisyti ir nepažeisti nusistovėjusių elgesio ir moralės normų, nepažeisti teisės aktų reikalavimų bei trečiųjų asmenų teisių ir teisėtų interesų, įskaitant teisės aktų, reglamentuojančių intelektinės nuosavybės apsaugą, asmens duomenų apsaugą, reklamos reguliavimą ir kitų;</p>
        <p>4.1.2. neatlikti jokių veiksmų, kurie prieštarauja taikytiniems teisės aktams, gerai moralei ar pažeidžia trečiųjų asmenų teises, įskaitant, bet neapsiribojant:</p>
        <p>4.1.2.1. nenaudoti Paslaugų ir (ar) Svetainės tokiu būdu, kuris gali sukelti pavojų BALDUGAMYBA.LT teikiamų paslaugų tinkamam veikimui, BALDUGAMYBA.LT serverio saugumui, vientisumui ar riboti BALDUGAMYBA.LT galimybes tinkamai teikti bet kokias paslaugas kitiems asmenims, o taip pat riboti kitų asmenų galimybę pasinaudoti bet kokiomis BALDUGAMYBA.LT teikiamomis paslaugomis;</p>
        <p>4.1.2.2. nelaikyti, neskelbti, nesiųsti, neplatinti arba bet kuriuo kitu būdu neperduoti bet kokio teisės aktų draudžiamo ar ribojamo, neteisingo, klaidinančio, šmeižikiško, grasinančio, diskriminacinio, apgaulingo, pornografinio, kurstančio tautinę, etninę, rasinę, religinę neapykantą, arba neapykantą dėl religijos neišpažinimo, asmenų teises pažeidžiančio Turinio, o taip pat bet kurio kito Turinio, kuris gali pažeisti teisės aktų reikalavimus, būtų laikomas pažeidžiančiu teisės aktuose įtvirtintas normas arba skatintų elgesį, priešingą teisės aktų reikalavimams arba sukeltų bet kokią teisinę atsakomybę BALDUGAMYBA.LT;</p>
        <p>4.1.2.3. neskelbti ir neplatinti nuorodų į bet kokį Turinį, kuris gali būti laikomas pažeidžiančiu taikytinų teisės aktų reikalavimus ar trečiųjų asmenų teises;</p>
        <p>4.1.2.4. nesinaudoti Paslaugomis ir (ar) Svetaine veiksmams, kurie galėtų pakenkti bet kuriems asmenims, jų turtui ar teisėtiems interesams, atlikti;</p>
        <p>4.1.2.5. neplatinti nepageidaujamos reklamos, kenkėjiškos programinės įrangos ir kito nepageidaujamo Turinio, taip pat nesiųsti elektroninių laiškų ir kitokių elektroninių pranešimų turint tikslą paveikti ar suprantant, kad tai paveiks kompiuterinių tinklų ar kompiuterinių tinklų savininkų turimos kompiuterinės įrangos veikimą;</p>
        <p>4.1.2.6. nesiūlyti prekių ir (ar) paslaugų, kuriomis prekyba prieštarauja teisės aktams ir (ar) moralės ir etikos normoms, ir kurios nurodytos šiame nebaigtiniame sąraše [Draudžiamų prekių ir paslaugų sąrašas];</p>
        <p>4.1.2.7. nenaudoti Svetainės ir (ar) Paslaugų neteisėtiems veiksmams ar sandoriams vykdyti arba sukčiavimui;</p>
        <p>4.1.2.8. nereklamuoti ir neskelbti informacijos, kurioje minimi su BALDUGAMYBA.LT tiesiogiai ar netiesiogiai konkuruojantys tretieji asmenys arba tokių asmenų prekės ir (ar) paslaugos, o taip pat nuorodos į tokius asmenis ir (ar) produktus. BALDUGAMYBA.LT konkurentais laikomi bet kokie asmenys, kurie kuria, rengia, valdo ar administruoja interneto svetaines, susijusias su įvairių prekių ir paslaugų pardavimo ir nuomos skelbimais, taip pat su tokiais tiesioginiais konkurentais susiję asmenys. BALDUGAMYBA.LT turi teisę nurodyti Klientui savo konkurentus ir tokie asmenys bus laikomi BALDUGAMYBA.LT konkurentais šio 4.1.2.8. punkto prasme nuo to momento, kai BALDUGAMYBA.LT apie juos informuos Klientą.</p>
        <p>4.1.2.9. nerinkti, nekaupti, neperkelti į kitas laikmenas, nepadaryti viešai prieinamais, neskelbti bei neplatinti Svetainės vartotojų duomenų ar duomenų apie bet kokius Svetainės vartotojų veiksmus, įskaitant duomenis apie siūlomas ir (ar) ieškomas prekes ir (ar) paslaugas, jų kainas ir t.t.;</p>
        <p>4.1.3. pateikti teisingą ir išsamią informaciją apie save, įskaitant tikrą savo vardą bei pavardę ar juridinio asmens rekvizitus, el. pašto adresą, taip pat nurodyti, ar Paslaugomis naudojasi kaip Verslininkas, ar kaip Privatus klientas pagal aukščiau Taisyklėse nurodytus kriterijus;</p>
        <p>4.1.4. pateikti objektyvią, teisingą, neklaidinančią, visapusišką ir išsamią informaciją apie siūlomas parduoti prekes ir (ar) paslaugas, įskaitant, bet neapsiribojant, kokybę, būklę, charakteristikas, gamintoją, kainą. Tokia informacija turi būti pateikiama ir valstybine kalba;</p>
        <p>4.1.5. saugoti Kliento prisijungimo vardą ir slaptažodį (jei tokie Klientui suteikti) tokiu būdu, kad jo nesužinotų tretieji asmenys, išskyrus asmenis, kuriuos Klientas įgaliojo atstovauti Klientą naudojantis Paslaugomis;</p>
        <p>4.1.6. nedelsdamas pranešti BALDUGAMYBA.LT apie bet kokius Kliento pateiktos informacijos (ypač pateiktos registruojantis Svetainėje) ir (ar) duomenų pasikeitimus pakeisdamas informaciją Svetainės anketoje;</p>
        <p>4.1.7. nedelsdamas el. paštu pranešti BALDUGAMYBA.LT, jei Kliento vartotojo vardas ir (ar) slaptažodis, kurie reikalingi naudotis Svetaine, buvo prarasti ar tapo žinomi tretiesiems asmenims;</p>
        <p>4.1.8. viename Skelbime reklamuoti ir (ar) skelbti ne daugiau kaip vieną prekę ir (ar) paslaugą, taip pat nereklamuoti ir (ar) neskelbti kelių tą pačią prekę ir (ar) paslaugą reklamuojančių Skelbimų;</p>
        <p>4.1.9. Skelbimus skelbti jų turinį atitinkančiose teminėse srityse;</p>
        <p>4.1.10. skelbiamame Skelbime teksto nerašyti didžiosiomis raidėmis;</p>
        <p>4.1.11. neskelbti beprasmių Skelbimų ar Skelbimų su beprasmėmis simbolių ir (ar) žodžių sekomis;</p>
        <p>4.1.12. viename skelbime reklamuoti vieną prekę / paslaugą, ne kelias;</p>
        <p>4.1.13. kontaktinę informaciją, prekių ir (ar) paslaugų aprašymus nurodyti išimtinai tik tam skirtose vietose. Skelbimo pavadinime nenaudoti internetinių svetainių adresų ir (ar) įmonių pavadinimų;</p>
        <p>4.1.14. užtikrinti, kad skelbimuose pateikiamose nuotraukose yra nurodyti tikrieji skelbimų tekste reklamuojami objektai, išskyrus atvejus, kai parduodamas naujas neišpakuotas daiktas. Taip pat užtikrinti, kad nuotraukos yra aiškios, be papildomų apipavidalinimų, grafinių elementų;</p>
        <p>4.1.15. Skelbimo nuotraukose nedėti jokių maketų, reklamų, įvairios tekstinės informacijos ir kt., išskyrus nedidelį Kliento logotipą ar vandens ženklą. „Siūlo darbą“ kategorijoje, galima dėti įmonės logotipą;</p>
        <p>4.1.16. atsiskaityti su BALDUGAMYBA.LT už teikiamas Mokamas paslaugas šių Taisyklių 6 straipsnyje numatyta tvarka.</p>
        <p>4.2. Naudodamasis bet kuria Paslauga Klientas patvirtina, kad jis:</p>
        <p>4.2.1. yra veiksnus asmuo ir (ar) teisėtai atstovaujantis juridiniam asmeniui ir (ar) kitiems tretiesiems asmenims, kurių vardu veikia, turintis visus įgaliojimus ir teises vykdyti sandorius, siūlomus Svetainėje;</p>
        <p>4.2.2. tinkamai vykdys savo pareigas, nurodytas Taisyklių 4.1.1. – 4.1.16. punktuose;</p>
        <p>4.2.3. supranta, kad Klientui gali kilti pareiga savo lėšomis sumokėti mokesčius, susijusius su naudojimusi Paslaugomis ir (ar) pajamomis, gautomis naudojantis Paslaugomis (pvz. gyventojų pajamų mokestį, PVM ir kt.);</p>
        <p>4.2.4. supranta ir sutinka, kad Klientui sutikus su šiomis Taisyklėmis tarp Kliento ir BALDUGAMYBA.LT sukuriami tik tokie teisiniai santykiai, kuriuos tiesiogiai ir aiškiai numato šios Taisyklės;</p>
        <p>4.2.5. supranta ir sutinka, kad tuo atveju jei vartotojo vardas ir slaptažodis, kurie reikalingi norint naudotis Svetaine, taps žinomi tretiesiems asmenims, tokie tretieji asmenys gali prisiimti įsipareigojimus, kurie taps privalomais Klientui ir įsipareigoja tokius įsipareigojimus prisiimti ir tinkamai vykdyti, o BALDUGAMYBA.LT neturi pareigos jokiu kitu būdu, išskyrus vartotojo vardo ir slaptažodžio patikrinimą, tikrinti vartotojo tapatybės;</p>
        <p>4.2.6. supranta ir sutinka, kad BALDUGAMYBA.LT tvarkytų ir valdytų Kliento asmens duomenis vadovaudamasi Lietuvos Respublikos teisės aktais bei Taisyklių 7 straipsniu;</p>
        <p>4.2.7. supranta ir sutinka, kad Kliento įkelti Skelbimai ir Turinys, išskyrus kontaktinius duomenis, gali būti rodomi ne tik Svetainėje, bet ir kituose BALDUGAMYBA.LT partnerių reklamos šaltiniuose (pavyzdžiui, www.autoplius.lt, www.aruodas.lt), jeigu yra papildomai užsakoma tokia Paslauga.</p>
        <p>4.3. Greta patvirtinimų, pateiktų taisyklių 4.2.1 – 4.2.7 punktuose, Klientai, kuriems yra nuo 7 iki 18 metų patvirtina, kad jis arba ji:</p>
        <p>4.3.1. prieš siūlydamas prekę ar paslaugą yra gavęs įstatyminių atstovų (pvz. tėvų) sutikimą siūlyti prekę ar paslaugą, sudaryti sandorį ir vykdyti iš jo kylančius įsipareigojimus;</p>
        <p>4.3.2. gerai suvokia visas Taisyklių nuostatas ir supranta, kad Svetainės ir Paslaugų naudojimas gali sukelti teisinę pareigą įsigyti ar parduoti prekę ar paslaugą.</p>

        <h2 class="my-8 text-xl font-bold">5. BALDUGAMYBA.LT TEISĖS IR PAREIGOS</h2>
        <p>5.1. BALDUGAMYBA.LT turi teisę:</p>
        <p>5.1.1. laikinai apriboti visos ar dalies Kliento Turinio pasiekiamumą, taip pat apriboti ar laikinai nutraukti visų ar dalies Paslaugų teikimą:</p>
        <p>5.1.1.1. jeigu Klientas nevykdo ar netinkamai vykdo šiose Taisyklėse prisiimtus įsipareigojimus ar nesilaiko nustatytų draudimų ar apribojimų;</p>
        <p>5.1.1.2. jeigu, BALDUGAMYBA.LT nuomone, to reikalauja atliekami techninės priežiūros ir (ar) Svetainės atnaujinimo darbai;</p>
        <p>5.1.1.3. jeigu to pareikalauja kompetentingos valdžios institucijos arba tai yra reikalinga Lietuvos Respublikos įstatymų bei kitų teisės aktų numatytais atvejais;</p>
        <p>5.1.1.4. jeigu tai yra reikalinga, siekiant apginti BALDUGAMYBA.LT ar trečiųjų asmenų teises ir teisėtus interesus;</p>
        <p>5.1.1.5. jeigu BALDUGAMYBA.LT įtaria, kad Klientas naudodamasis Paslaugomis sukėlė ar gali sukelti grėsmę kitų Svetainės Klientų saugumui;</p>
        <p>5.1.1.6. jeigu Klientas naudodamasis Paslaugomis, Svetaine ir (ar) keldamas Skelbimus daro žalą BALDUGAMYBA.LT, įskaitant, bet neapsiribojant BALDUGAMYBA.LT geram vardui ir (ar) reputacijai;</p>
        <p>5.1.1.7. kitais Taisyklėse nurodytais atvejais;</p>
        <p>5.1.2. bet kada apriboti Kliento galimybę skelbi Skelbimus ir (ar) kitą Turinį, įskaitant komentarus ir (ar) tiesiogines žinutes bei savo nuožiūra pašalinti iš Svetainės Skelbimus ar bet kokį kitą Turinį, įskaitant Kliento paliktus komentarus ir (ar) tiesiogines žinutes, jei, BALDUGAMYBA.LT nuomone, jie pažeidžia šių Taisyklių nuostatas, taikomus teisės aktus arba yra priešingi gerai moralei;</p>
        <p>5.1.3. keisti Skelbimus ir bet kokį kitą Turinį, įskaitant, bet neapsiribojant Kliento statuso pakeitimą iš Privataus kliento į Verslininką, jei Klientas klaidingai pasirinko Kliento statusą ar pateikė klaidingą informaciją ir (ar) pažeidė šių Taisyklių nuostatas;</p>
        <p>5.1.4. BALDUGAMYBA.LT turi teisę bet kada Svetainės ribose savo nuožiūra pakeisti ar pertvarkyti Skelbimus, perkelti juos į kitas temines sritis nekeisdama Kliento informacijos, tam, kad Svetaine būtų patogiau naudotis;</p>
        <p>5.1.5. BALDUGAMYBA.LT turi teisę (bet ne pareigą) bet kada stebėti Kliento veiksmus Svetainėje, įskaitant Kliento Skelbimų ir (ar) tiesioginių žinučių bei komentarų stebėjimą. Naudodama teisėtas priemones BALDUGAMYBA.LT turi teisę tirti bet kokius Taisyklių pažeidimus;</p>
        <p>5.1.6. BALDUGAMYBA.LT turi teisę savo nuožiūra panaikinti Kliento paskyrą, jei Klientas yra gavęs ne mažiau nei du neigiamus kito Kliento atsiliepimus ar komentarus. Klientui gavus trečiąjį neigiamą komentarą ar atsiliepimą iš kito Kliento, BALDUGAMYBA.LT panaikins Kliento paskyrą. Taip pat BALDUGAMYBA.LT turi teisę savo nuožiūra panaikinti Kliento paskyrą, jei Klientas yra pažeidęs Taisykles daugiau nei 3 kartus. Klientas turi teisę pateikti skundą dėl sprendimo panaikinti paskyrą atsiųsdamas el. laišką adresu info@BALDUGAMYBA.LT. BALDUGAMYBA.LT sprendimas yra galutinis;</p>
        <p>5.1.7. BALDUGAMYBA.LT turi teisę be perspėjimo panaikinti Kliento paskyrą, jei prie jos nebuvo prisijungta daugiau kaip 2 (du) metus ir paskyros likutis yra iki 1,45 Eur;</p>
        <p>5.1.8. BALDUGAMYBA.LT turi teisę be perspėjimo panaikinti Kliento paskyrą, jei prie jos nebuvo prisijungta daugiau kaip 5 (penkerius) metus, jeigu paskyros likutis yra virš 1,45 Eur;</p>
        <p>5.1.9. BALDUGAMYBA.LT turi teisę gauti užmokestį už suteikiamas Paslaugas pagal Svetainėje nurodytas kainas. Tam tikslui, Klientui pareikalavus, BALDUGAMYBA.LT pateiks Klientui sąskaitą;</p>
        <p>5.1.10. Klientui pažeidus jo įsipareigojimus, nurodytus Taisyklių 4.1.1. – 4.1.16. punktuose, BALDUGAMYBA.LT turi teisę reikalauti Kliento sumokėti sutartinę baudą, lygią 29 Eur;</p>
        <p>5.1.11. be atskiro pranešimo Klientui pasitelkti trečiuosius asmenis bet kokiems veiksmams, susijusiems su šiomis Taisyklėmis, atlikti, taip pat tretiesiems asmenims perleisti savo teises bei pareigas, kylančias iš šių Taisyklių ar dalį jų.</p>
        <p>5.1.12. be atskiro pranešimo Klientui pašalinti Kliento įkeltas nuotraukas, kuriose yra matomas daugiau nei vienas BALDUGAMYBA.LT vandens ženklas.</p>
        <p>5.2. Apie sankcijas, kurios bus pritaikytos už Taisyklių pažeidimą, Klientas informuojamas registracijos metu nurodytu el. paštu. Taisyklių pažeidimo atveju, papildomos užsakytos Paslaugos yra anuliuojamos ir pinigai nėra gražinami.</p>
        <p>5.3. Verslininkas bus įspėjamas nurodytu kontaktiniu el. paštu ne anksčiau nei prieš 30 dienų apie BALDUGAMYBA.LT sprendimą nutraukti Paslaugų teikimą ir kartu informuojamas apie tokio sprendimo motyvus. Šis pranešimo terminas nėra taikomas tuo atveju, jeigu Verslininkas keletą kartų sistemingai pažeidė Taisykles ir dėl to yra nutraukiamas Paslaugų teikimas. Tokiu atveju, Verslininką dėl tokio sprendimo motyvų BALDUGAMYBA.LT informuoja el. paštu nepagrįstai nedelsdamas.</p>
        <p>5.4. Šalys susitaria, kad BALDUGAMYBA.LT turi teisę bet kada nutraukti Svetainės veiklą.</p>

        <h2 class="my-8 text-xl font-bold">6. MOKAMOS PASLAUGOS</h2>
        <p>6.1. Mokamos Paslaugos bei jų naudojimosi tvarka yra apibūdinta ir nurodyta Svetainėje, o jų kaina nurodyta kiekvienos konkrečios Mokamos Paslaugos užsakymo puslapyje.
        <p>6.2. Klientas supranta ir sutinka, kad Mokamos Paslaugos gali būti teikiamos tik po to, kai Klientas sumoka BALDUGAMYBA.LT už Mokamas Paslaugas Svetainėje nurodyta tvarka. BALDUGAMYBA.LT turi teisę bet kada vienašališkai pakeisti užmokesčio už bet kurias Mokamas Paslaugas dydį bei mokėjimo tvarką.</p>
        <p>6.3. Apribojus ar sustabdžius Kliento galimybę naudotis Mokamomis Paslaugomis ar Klientui negavus ar laiku negavus Mokamų Paslaugų dėl kitų priežasčių nei Kliento įvykdytas šių Taisyklių pažeidimas bei atvejį, nurodytą šių Taisyklių 5.1.6 punkte, BALDUGAMYBA.LT, Kliento prašymu, įsipareigoja pratęsti Mokamų Paslaugų teikimą Klientui tam laikotarpiui, kurį nebuvo teikiamos Mokamos Paslaugos, arba neatlygintinai suteikti Mokamas Paslaugas analogiškas nesuteiktoms Mokamoms Paslaugoms (jei Mokamos Paslaugos nėra tęstinio pobūdžio).</p>
        <p>6.4. Užmokestis už Skelbimus ir Turinį, kurie buvo panaikinti ir (ar) pašalinti dėl to, jog Klientas pažeidė šių Taisyklių nuostatas, negrąžinamas.</p>
        <p>6.5. BALDUGAMYBA.LT turi teisę Svetainės būtinų profilaktinių darbų metu apriboti ar nutraukti Paslaugų teikimą Klientams protingam terminui. Tokiu atveju Klientas, besinaudojantis Mokamomis Paslaugomis, yra informuojamas apie profilaktinių darbų pradžią pranešimu (priklausomai nuo to, kokiomis Paslaugomis naudojasi Klientas – elektroniniu paštu ir (ar) kitokiu pranešimu) ne vėliau kaip prieš 24 val., iki darbų pradžios. Tokiu atveju BALDUGAMYBA.LT gali, tačiau neprivalo, pratęsti Mokamų Paslaugų teikimą Klientui tam laikotarpiui, kurį nebuvo teikiamos Mokamos Paslaugos, arba neatlygintinai suteikti Mokamas Paslaugas, analogiškas nesuteiktoms Mokamoms Paslaugoms (jei Mokamos Paslaugos nėra tęstinio pobūdžio).</p>
        <p>6.6. Vienas Mokamos Paslaugos užsakymas Klientui suteikia teisę įdėti vieną Skelbimą, nebent prie konkrečios Paslaugos yra nurodyta kitaip. Pasirinkęs Mokamą Paslaugą konkrečiam laikotarpiui (pavyzdžiui, 30 dienų, 60 dienų ar pan.), Klientas įsipareigoja šia Paslauga naudotis ne trumpiau nei Mokamos Paslaugos visas galiojimo laikotarpis (toliau – Minimalus laikotarpis). Jei Skelbimo sandoris įvyksta anksčiau, nei pasibaigia Minimalus laikotarpis (pavyzdžiui, prekė parduodama ar pan.), arba jei Klientas pats panaikina Skelbimą, arba jei Skelbimas panaikinamas dėl Kliento kaltės, pinigai už nepanaudotą Minimalų laikotarpį Klientui nėra grąžinami ir nėra perkeliami kitam Skelbimui apmokėti. Įvykus Skelbimo sandoriui Klientas privalo pašalinti Skelbimą, kad neklaidintų kitų Svetainės lankytojų.</p>
        <p>6.7. Klientui perkėlus Skelbimą iš aktyvaus į pasyvų, taip pat sustabdžius Skelbimo rodymą dėl Kliento kaltės, Skelbimo nerodymo laikotarpis yra įskaitomas į Minimalų laikotarpį ir Minimalus laikotarpis neperkeliamas bei neprailginamas laikotarpiui, kurį Skelbimas nebuvo rodomas viešai Svetainėje.</p>
        <p>6.8. Įvykus Skelbimo sandoriui (turto pardavimas, nuoma ar pan.), Minimalaus laikotarpio likutis nėra perkeliamas kitam Skelbimui ir Klientas negali skelbti naujo (kito) Skelbimo vietoje seno Skelbimo. Jei Klientas Mokamą Paslaugą pritaikė (ketina pritaikyti) kitam Skelbimui, BALDUGAMYBA.LT turi teisę panaikinti šį Skelbimą ir perspėti Klientą arba reikalauti už tokį Skelbimą apmokėti kaip už naujai paskelbtą Skelbimą. Toks Skelbimas imamas rodyti tik už jį tinkamai apmokėjus. Klientui nesutikus apmokėti, Skelbimas yra panaikinamas.</p>
        <p>6.9. Jei sutartis dėl Paslaugų teikimo dėl Kliento kaltės ar jo iniciatyva yra nutraukiama nepraėjus Minimaliam laikotarpiui, Klientas privalo sumokėti BALDUGAMYBA.LT kompensaciją, lygią konkrečios Kliento užsakytos Mokamos Paslaugos mokesčio daliai nuo atsisakymo dienos iki Minimalaus laikotarpio pabaigos. Ši kompensacija išskaičiuojama iš Kliento sumokėtos Mokamos Paslaugos kainos.</p>

        <h2 class="my-8 text-xl font-bold">7. ASMENS DUOMENYS</h2>
        <p>7.1. Registracijos metu ar vėliau naudojantis Svetaine Kliento pateiktus ar BALDUGAMYBA.LT kitais būdais surinktus asmens duomenis BALDUGAMYBA.LT tvarko, t. y. renka, naudoja, saugo, perduoda, tik teisėtai, skaidriai ir sąžiningai, iš anksto nustatytais tikslais, ir tik tokia apimtimi, kuri reikalinga tikslams pasiekti. Kliento asmens duomenis BALDUGAMYBA.LT tvarko vadovaujantis šiose Taisyklėse, taip pat BALDUGAMYBA.LT Privatumo politikos nustatyta tvarka.</p>
        <p>7.2. BALDUGAMYBA.LT užtikrina Klientų, kaip duomenų subjektų, teises pagal Bendrąjį asmens duomenų apsaugos reglamentą, Lietuvos Respublikos asmens duomenų teisinės apsaugos įstatymą ir kitus asmens duomenų tvarkymą reglamentuojančius norminius teisės aktus. Klientų, kaip asmens duomenų subjektų, teisės ir jų įgyvendinimo tvarka nustatyta BALDUGAMYBA.LT Privatumo politikoje.</p>

        <h2 class="my-8 text-xl font-bold">8. INFORMACIJOS APSAUGOS PRIEMONĖS</h2>
        <p>8.1. BALDUGAMYBA.LT Kliento asmens duomenis tvarko tokiu būdu, kad taikant atitinkamas technines ar organizacines priemones būtų užtikrintas tinkamas asmens duomenų saugumas, įskaitant apsaugą nuo duomenų tvarkymo be leidimo arba neteisėto duomenų tvarkymo ir nuo netyčinio praradimo, sunaikinimo ar sugadinimo.</p>
        <p>8.2. BALDUGAMYBA.LT primena, jog Klientas yra pats atsakingas už prisijungimo duomenų slaptumą. BALDUGAMYBA.LT prašo būti atsargiam naudojant ir saugant prisijungimo duomenis. Klientas turėtų atsijungti nuo naršyklės baigęs darbą tam, kad būtų tikras, jog niekas neprieis prie Kliento elektroninio pašto, asmeninės informacijos, ypač tais atvejais, kai Klientas naudojasi viešai prieinamu kompiuteriu (pavyzdžiui, interneto kavinėje, bibliotekoje).</p>

        <h2 class="my-8 text-xl font-bold">9. ATSAKOMYBĖS RIBOJIMAS</h2>
        <p>9.1. Klientas sutinka, kad BALDUGAMYBA.LT nėra ir nebus atsakingas už Svetainės ir (ar) Paslaugų veikimo sutrikimus, kilusius ne dėl BALDUGAMYBA.LT kaltės, ir dėl to Kliento ar trečiųjų asmenų patirtus nuostolius ar žalą.</p>
        <p>9.2. BALDUGAMYBA.LT nebus atsakingas už daiktų ir (ar) paslaugų, parduodamų ar įsigyjamų naudojantis Svetaine ir (ar) Paslaugomis, kokybę, kiekį ir (ar) komplektiškumą.
        <p>9.3. Klientas supranta ir sutinka su tuo, kad Svetainė ir (ar) Paslaugos veikia taip, kokios yra (angl. service as-is) principu ir todėl yra pateikiamos be jokių patvirtinimų ar garantijų iš BALDUGAMYBA.LT pusės dėl to, jog Svetainė veiks ir Paslaugos bus teikiamos tinkamai ir laiku, be sutrikimų, kokybiškai, pilna apimtimi arba kad tai nesukels jokių neigiamų pasekmių Klientui ar tretiesiems asmenims. BALDUGAMYBA.LT nėra ir nebus atsakingas už Svetainėse esančios informacijos neteisėtumą, neatitikimus, netikslumą ar klaidingumą (išskyrus tą informaciją, kurią pateikia pats BALDUGAMYBA.LT) ir iš to kilusias neigiamas pasekmes Klientui ar tretiesiems asmenimis.</p>
        <p>9.4. BALDUGAMYBA.LT neatsako už jokią žalą ir (ar) nuostolius, kuriuos gali patirti Klientas naudodamasis Svetaine ir (ar) Paslaugomis bei siųsdamas, patalpindamas ir bet kuriais kitais būdais perduodamas ar padarydamas viešai prieinamu bet kokią informaciją, įskaitant ir komentarus ir (ar) tiesiogines žinutes.</p>
        <p>9.5. Klientas supranta ir sutinka, kad BALDUGAMYBA.LT, atsižvelgiant į šių Taisyklių 9.1. punktą bei 9.3. punktą, niekada ir dėl jokių priežasčių nebus atsakingas už visus ir bet kuriuos savo veiksmus arba neveikimą susijusį su Kliento naudojimusi Svetaine ir (ar) Paslaugomis ir šių Taisyklių laikymusi. Klientas prisiima visą atsakomybę dėl bet kokio pobūdžio žalos ar nuostolių atlyginimo, kurie jam ar tretiesiems asmenims gali atsirasti bet kokiu būdu Klientui naudojantis Svetaine ar Paslaugomis, ar jose esančia informacija.</p>
        <p>9.6. Klientas įsipareigoja užtikrinti, kad BALDUGAMYBA.LT niekada nekiltų jokia teisinė atsakomybė, pareiga apmokėti, atlyginti ar kitaip kompensuoti bet kokius nuostolius, žalą ar kitokias išlaidas, atsiradusias dėl to, kad Klientas naudojosi Svetaine ir (ar) Paslaugomis.</p>
        <p>9.7. Klientas supranta ir sutinka su tuo, jog BALDUGAMYBA.LT nėra ir nebus atsakingas už dėl trečiųjų asmenų, įskaitant, bet tuo neapsiribojant, internetinio, mobilaus ryšio teikėjų, elektroninio pašto paslaugos teikėjo ar kt., kaltės Klientui nesuteiktas ar laiku nesuteiktas Paslaugas. Klientui negalint naudotis Mokamomis Paslaugomis dėl trečiųjų asmenų kaltės, užmokestis už Mokamas Paslaugas Klientui nėra grąžinamas.</p>
        <p>9.8. BALDUGAMYBA.LT atsakomybė Klientui ar tretiesiems asmenims, kylanti iš šių Taisyklių, yra ribojama – 29 Eur suma.</p>

        <h2 class="my-8 text-xl font-bold">10. TAISYKLIŲ KEITIMAS</h2>
        <p>10.1. BALDUGAMYBA.LT pasilieka teisę bet kada savo išimtine nuožiūra keisti, taisyti ar papildyti šias Taisykles dėl bet kokių teisėtų, pavyzdžiui, teisinių, norminių ar saugumo priežasčių, atsižvelgdamas į galiojančių teisės aktų nustatytus reikalavimus.</p>
        <p>10.2. Pakeistos Taisyklės bus pateiktos patvarioje laikmenoje Verslininkui susipažinti el. paštu, kurį Verslininkas pateikė registruodamasis Svetainėje likus ne mažiau kaip 15 dienų iki numatytos pakeistų Taisyklių įsigaliojimo dienos. Taisyklės taip pat bus pateiktos Klientui susipažinti naudojantis Svetaine. Laikoma, kad BALDUGAMYBA.LT ir Klientas faktiškai susitarė dėl pakeistų Taisyklių taikymo, jeigu:</p>
        <p>10.2.1. Klientas nepateiks prieštaravimo dėl Taisyklių pakeitimų iki numatytos pakeistų Taisyklių įsigaliojimo dienos ir toliau naudosis Svetaine;</p>
        <p>10.2.2. Klientas buvo aiškiai informuotas apie pakeitimus.</p>
        <p>10.3. Jeigu Klientas nesutinka su pakeistomis ir (ar) papildytomis Taisyklėmis, jis praranda teisę naudotis Svetaine ir (ar) Paslaugomis.</p>
        <p>10.4. Verslininkas turi teisę nutraukti sudarytą sutartį su BALDUGAMYBA.LT dėl keičiamų Taisyklių, jeigu praneša apie sutarties nutraukimą BALDUGAMYBA.LT iki pakeistų Taisyklių įsigaliojimo momento. Toks sutarties nutraukimas įsigalioja per 15 dienų nuo pranešimo apie keičiamas Taisykles gavimo. Šio termino Verslininkas gali atsisakyti rašytiniu pareiškimu arba savo veiksmas išreikšdamas tokį norą.</p>
        <p>10.5. Jeigu Verslininkas, nepraėjus 15 dienų terminui dėl sutarties nutraukimo, toliau naudodamasis Paslaugomis ar Svetaine, įskaitant, bet neapsiribojant Paslaugų pratęsimu, naujų Paslaugų užsakymu, Skelbimų redagavimu ir (ar) atnaujinimu, po to, kai įsigalios Taisyklių pakeitimai, patvirtina, kad jis susipažino su tokiais pakeitimais ir visiškai su jais sutinka.</p>
        <p>10.6. Iki Taisyklių pakeitimo Klientų užsakytos Paslaugos teikiamos tokia tvarka ir terminais, kaip buvo nustatyta tuo metu galiojusiose Taisyklėse.</p>
        <p>10.7. BALDUGAMYBA.LT taip pat turi teisę iš anksto nepranešdamas Klientui vienašališkai pakeisti ir atnaujinti šių Taisyklių 4.1.2.6 punkte nurodytą prekių ir (ar) paslaugų, kurių prekyba prieštarauja teisės aktams ir (ar) moralės ir etikos normoms, sąrašą.</p>

        <h2 class="my-8 text-xl font-bold">11. PASLAUGŲ PAKEITIMAI</h2>
        <p>11.1. Klientas sutinka, jog BALDUGAMYBA.LT bet kuriuo metu gali toliau plėtoti Svetainę bei siūlomų Paslaugų spektrą siekdamas užtikrinti tinkamą Paslaugų teikimą ar dėl kitų su tuo susijusių priežasčių (pavyzdžiui, pasikeitus techniniams reikalavimams ar saugos aspektams), taip pat siekdamas užtikrinti teikiamų Paslaugų kokybę, pasiūlą bei prisitaikyti prie Klientų poreikių. Todėl BALDUGAMYBA.LT gali vienašališkai keisti teikiamas Paslaugas ir (ar) jų apmokestinimą, tokiu atveju Klientas neturės galimybės toliau naudotis nepakeistomis Paslaugomis po pakeitimų įsigaliojimo.</p>
        <p>11.2. Dėl tokių Paslaugų pakeitimų Privatus klientas nepatirs jokių papildomų išlaidų. Apie Paslaugų pakeitimus ir Privataus kliento teisę atsisakyti sutarties dėl Mokamų Paslaugų BALDUGAMYBA.LT Privatų klientą informuos el. paštu 30 dienų prieš įsigaliojant pakeitimams, pateikdamas informaciją susipažinimui apie planuojamus Paslaugų pakeitimus.</p>
        <p>11.3. Privatus klientas turės teisę atsisakyti sutarties dėl Mokamų Paslaugų teikimo per 30 dienų nuo pranešimo apie pakeitimus gavimo arba nuo pakeitimų taikymo momento (priklausomai nuo to, kas įvyko vėliau), jei Paslaugų pakeitimas turės neigiamos įtakos Privataus kliento prieigai prie Mokamų Paslaugų bei naudojimuisi jomis, išskyrus atvejus, kai toks neigiamas poveikis yra nedidelis.</p>
        <p>11.4. Jeigu aiškiai nenurodyta kitaip, Klientas sutinka, kad apie bet kokius Paslaugų pakeitimus jam bus pranešta prieš 30 dienų nuo jų taikymo pradžios el. paštu, kurį Klientas pateikė BALDUGAMYBA.LT registruodamasis Svetainėje.</p>
        <p>11.5. Klientas aiškiai sutinka ne rečiau kaip kartą per mėnesį tikrinti savo el. paštą, kurį pateikė BALDUGAMYBA.LT registruodamas savo paskyrą.</p>

        <h2 class="my-8 text-xl font-bold">12. PRIVATAUS KLIENTO TEISĖS MOKAMŲ PASLAUGŲ NETEIKIMO METU ARBA NETINKAMOS KOKYBĖS PASLAUGŲ TEIKIMO ATVEJU</h2>
        <p>12.1. Privatus klientas turi teisę pareikšti reikalavimą BALDUGAMYBA.LT pradėti teikti Mokamas Paslaugas, jeigu BALDUGAMYBA.LT nevykdo savo pareigos pradėti teikti Privataus kliento įsigytas Mokamas Paslaugas nedelsiant po sutarties sudarymo, nebent tarp šalių yra sulygta kitaip. Jeigu pateikus tokį reikalavimą BALDUGAMYBA.LT neteikia Mokamų Paslaugų nedelsdama ar per sutarties šalių aiškiai sutartą papildomą terminą, Privatus klientas turi teisę vienašališkai nutraukti sutartį dėl Mokamų Paslaugų teikimo.</p>
        <p>12.2. Jeigu yra suteiktos netinkamos kokybės Mokamos paslaugos, Privatus klientas turi teisę reikalauti ištaisyti Mokamų paslaugų trūkumus, sumažinti kainą arba vienašališkai nutraukti sutartį.</p>
        <p>12.3. Privatus klientas turi teisę į Mokamos Paslaugos trūkumų ištaisymą, išskyrus atvejus, kai to neįmanoma padaryti, arba jeigu dėl to BALDUGAMYBA.LT patirtų neproporcingų išlaidų, atsižvelgiant į visas aplinkybes, įskaitant:</p>
        <p>12.3.1. Mokamos Paslaugos vertę, jeigu nebūtų trūkumų;</p>
        <p>12.3.2. trūkumų reikšmingumą.</p>
        <p>12.4. Privatus klientas turi teisę į Mokamos Paslaugos kainos sumažinimą arba teisę į vienašališką sutarties nutraukimą bet kuriuo iš šių atvejų:</p>
        <p>12.4.1. BALDUGAMYBA.LT neįmanoma ištaisyti Mokamos Paslaugos trūkumų arba dėl to BALDUGAMYBA.LT patirtų neproporcingų išlaidų atsižvelgiant į visas aplinkybes;</p>
        <p>12.4.2. BALDUGAMYBA.LT neištaisė Mokamos Paslaugos trūkumų per protingą terminą, nemokamai ir nesukeldama Privačiam klientui didelių nepatogumų, atsižvelgiant į Mokamos Paslaugos pobūdį, dėl kurio ji buvo reikalinga Privačiam klientui;</p>
        <p>12.4.3. Mokamos Paslaugos trūkumų atsirado po to, kai BALDUGAMYBA.LT bandė užtikrinti tinkamą Mokamos Paslaugos kokybę;</p>
        <p>12.4.4. trūkumas yra esminis;</p>
        <p>12.4.5. BALDUGAMYBA.LT pareiškė arba iš aplinkybių tapo aišku, kad ji per protingą terminą neištaisys Mokamos Paslaugos trūkumų arba tai sukels didelių nepatogumų Privačiam klientui.</p>
        <p>12.5. Privatus klientas turi teisę nutraukti sutartį tik tuo atveju, kai Mokamos Paslaugos trūkumas nėra nedidelis.</p>
        <p>12.6. Privatus klientas savo teisę nutraukti sutartį įgyvendina pateikdamas BALDUGAMYBA.LT pareiškimą, kuriame yra išreiškiamas jo sprendimas nutraukti sutartį dėl Mokamų Paslaugų teikimo dėl netinkamos kokybės. Nutraukus sutartį, BALDUGAMYBA.LT Privačiam klientui ne vėliau kaip per 14 dienų grąžina visas jo sumokėtas sumas už laikotarpį, kurį buvo teikiamos netinkamos kokybės Mokamos Paslaugos, tokiu pačiu mokėjimo būdu, kokį naudojo Privatus klientas mokėdamas už Mokamas Paslaugas.</p>

        <h2 class="my-8 text-xl font-bold">13. REITINGO NUSTATYMAS</h2>
        <p>13.1. BALDUGAMYBA.LT Skelbimų paieškos algoritmas atsižvelgia į toliau išvardintus veiksnius generuojant Skelbimų paieškos rezultatus. Jis sukurtas taip, kad Klientai rastų aktualius Skelbimus, ir gali kiekvienam Klientui būti suasmenintas atsižvelgiant į tokius veiksnius kaip, pavyzdžiui, Kliento pasirinktas paieškos rezultatų rodymo filtras.
        <p>13.2. Rikiuojant Skelbimų paieškos rezultatus, BALDUGAMYBA.LT remiasi toliau pateikiamais parametrais (svarbos tvarka):</p>
        <p>13.2.1. Didesnį užsakytų žvaigždučių skaičių turintys skelbimai rodomi aukščiau. Žvaigždutes Skelbimui gali užsisakyti visi Klientai. Jei žvaigždučių kiekis vienodas, aukščiau rodomas Skelbimas, kurio žvaigždutės buvo užsakytos ilgesniam laikui. Daugiau informacijos kaip veikia Skelbimo iškėlimas žvaigždutėmis galite rasti „Dažniausiai užduodami klausimai“.
        <p>13.2.2. Jeigu žvaigždučių Skelbimai neturi, tuomet jų tarpusavio rikiavimo kriterijus nurodomas sąrašo viršuje. Galimi kriterijai: (i) Naujausi viršuje, (ii) Atnaujinti viršuje, (iii) Pigiausi viršuje, (iv) Brangiausi viršuje. Automatiškai Svetainėje yra taikomas rikiavimas pagal Skelbimų atnaujinimo datą t. y. aukščiau rodomi tie Skelbimai, kurie buvo atnaujinti vėliau. Kategorijos, kuriose Skelbimai rikiuojami pagal Skelbimo įdėjimo datą, o ne atnaujinimo: (i) Nekilnojamasis turtas (išskyrus Medžiagos, įranga; Statybos paslaugos; Kita) ir (ii) Auto dalys. Lankytojui pakeitus rikiavimo kriterijų, Skelbimų sąrašas atitinkamai perdėliojamas ignoruojant Skelbimų žvaigždučių kiekį.</p>
        <p>13.2.3. Atlikus tekstinę paiešką pagal raktažodį, Skelbimai tarpusavyje rikiuojami pagal tai, kiek jie atitinka paiešką, pvz., ar raktažodis buvo rastas Skelbimo antraštėje, ar Skelbimo kategorijos pavadinime, ar aprašyme, kiek kartų jis pasikartoja ir pan. Jei tarp rezultatų yra Skelbimų su žvaigždutėmis, tuomet jie rodomi aukščiau pagal 13.2.1. punkto tvarką. Lankytojai gali pasikeisti rikiavimo kriterijų, tuomet Skelbimų sąrašas atitinkamai perdėliojamas ignoruojant Skelbimų žvaigždučių kiekį.</p>
        <p>13.3. Dalis Skelbimų yra importuojami į BALDUGAMYBA.LT iš kitų portalų (BALDUGAMYBA.LT, Autoplius.lt, CVbankas.lt), kai Klientas perka „2in1“ paslaugą: įkelia skelbimą į pvz., Autoplius.lt ir skelbimas automatiškai yra įkeliamas ir į BALDUGAMYBA.LT. Tokie perkelti skelbimai automatiškai yra rodomi žemiau negu Klientų tiesiogiai BALDUGAMYBA.LT paskelbti Skelbimai. Jeigu Klientas pats pasirenka rikiavimo kriterijų, tuomet sąrašas atitinkamai perdėliojamas ignoruojant Skelbimų importavimo faktą.</p>
        <p>13.4. Visi Klientai gali pirkti žvaigždutes, atnaujinti savo Skelbimus arba juos įvesti iš naujo taip siekiant iškelti Skelbimus į paieškos rezultatų pradžią.

        <h2 class="my-8 text-xl font-bold">14. TEISĖ ATSISAKYTI SUTARTIES</h2>
        <p>14.1. Privatus klientas patvirtina, kad sutinka, jog apmokėjus Skelbimo patalpinimą BALDUGAMYBA.LT bei įsigijus kitas papildomas Paslaugas, jos yra laikomos pradėtomis teikti iš karto ir jų teikimas negali būti atšauktas, todėl Privatus klientas sutinka, jog jam netaikoma 14 dienų nuotolinės sutarties atsisakymo teisė. Todėl Privatus klientas, prieš užsakydamas ir apmokėdamas Paslaugas, privalo įsivertinti jų poreikį. Privačiam klientui pašalinus Skelbimą, padarius jį nematomu (pasyviu), pinigai už papildomai užsakytą Paslaugą nėra grąžinami ir jos galiojimo terminas nėra pratęsiamas ar perkeliamas kitam Skelbimui.</p>
        <p>14.2. Jeigu sutartis dėl Kliento kaltės ar jo iniciatyva yra nutraukiama nepraėjus Minimaliam laikotarpiui, Klientas privalo sumokėti BALDUGAMYBA.LT kompensaciją, lygią konkrečios Kliento Mokamos Paslaugos mokesčio daliai nuo atsisakymo dienos iki Minimalaus laikotarpio pabaigos. Ši kompensacija išskaičiuojama iš Kliento sumokėtos Mokamos Paslaugos kainos. Ši nuostata nėra taikoma tuo atveju, jeigu Privatus klientas nutraukia sutartį dėl pasikeitusio Mokamų Paslaugų teikimo, jų neteikimo ar netinkamos kokybės pagal sutarties nutraukimo tvarką, išdėstytą Taisyklių 11 ir 12 skyriuose.</p>

        <h2 class="my-8 text-xl font-bold">15. DUOMENŲ NAUDOJIMAS</h2>
        <p>15.1. Registracijos metu ar vėliau naudojantis BALDUGAMYBA.LT Kliento pateiktus ar BALDUGAMYBA.LT kitais būdais surinktus asmens ir kitus duomenis (toliau – Duomenys) BALDUGAMYBA.LT tvarko, t. y. renka, naudoja, saugo, perduoda, tik teisėtai, skaidriai ir sąžiningai, iš anksto nustatytais tikslais, ir tik tokia apimtimi, kuri reikalinga tikslams pasiekti. Kliento Duomenis BALDUGAMYBA.LT tvarko vadovaujantis šiose Taisyklėse, taip pat BALDUGAMYBA.LT Privatumo politikos nustatyta tvarka.</p>
        <p>15.2. Duomenys tvarkomi siekiant tinkamai suteikti Paslaugas Klientams (patalpinti Skelbimus, užsakyti tam tikrą Paslaugą ir pan.). Kliento Duomenys taip pat yra tvarkomi jo registravimo bei Skelbimų duomenų bazės administravimo Svetainės sistemoje tikslu bei tiesioginės rinkodaros ir reklaminių akcijų (tiesioginės rinkodaros žaidimų, viktorinų, konkursų) vykdymo tikslais. BALDUGAMYBA.LT renka ir saugo Duomenis elektroniniu būdu, Klientas gali matyti visus savo pateiktus Duomenis prisijungus prie savo paskyros tol, kol ji egzistuoja. Ištrynus paskyrą, Klientai netenka prieigos prie įkeltų Duomenų ir Turinio.</p>
        <p>15.3. BALDUGAMYBA.LT garantuoja, kad Duomenys nebus parduodami, teikiami ar kitaip be teisėto pagrindo perduodami tretiesiems asmenims, taip pat naudojami kitiems tikslams, nei jie buvo surinkti. BALDUGAMYBA.LT neperduoda Duomenų niekaip kitaip, kaip tik vadovaudamasis Privatumo politika ar taikytinais teisės aktais.</p>

        <h2 class="my-8 text-xl font-bold">16. GARANTIJA</h2>
        <p>16.1. BALDUGAMYBA.LT Privačiam klientui primena apie galiojančią skaitmeninio turinio ir skaitmeninių paslaugų kokybės garantiją pagal įstatymą.

        <h2 class="my-8 text-xl font-bold">17. ATSILIEPIMAI</h2>
        <p>17.1. Svetainėje galima palikti atsiliepimus apie parduodamus objektus Skelbimuose.</p>
        <p>17.2. Atsiliepimų autentiškumas Svetainėje yra užtikrinamas.</p>

        <h2 class="my-8 text-xl font-bold">18. MEDIACIJA</h2>
        <p>18.1. Jeigu Verslininkas arba BALDUGAMYBA.LT bet kuriuo metu išreiškia pageidavimą, kad kilęs ginčas būtų sprendžiamas mediacijos būdu, BALDUGAMYBA.LT bendradarbiauja su šiais mediatoriais, apie kuriuos plačiau galima pasiskaityti čia ir čia, tačiau BALDUGAMYBA.LT ir Verslininkas gali bendrai susitarti ir dėl kito mediatoriaus, jeigu tam yra poreikis.</p>

        <h2 class="my-8 text-xl font-bold">19. TAIKYTINA TEISĖ IR GINČŲ SPRENDIMAS</h2>
        <p>19.1. Taisyklėms yra taikoma Lietuvos Respublikos teises.</p>
        <p>19.2. Visi tarp BALDUGAMYBA.LT ir Kliento kilę nesutarimai dėl šių Taisyklių vykdymo yra sprendžiami derybų keliu. Šalims neišsprendus ginčo derybų būdu toks ginčas galutinai sprendžiamas Lietuvos Respublikos įstatymų nustatyta tvarka teismuose Lietuvos Respublikos įstatymų nustatyta tvarka.</p>
        <p>19.3. BALDUGAMYBA.LT turi savo vidinę nemokamą Verslininkų skundų nagrinėjimo sistemą (toliau – Sistema). Norėdamas pasinaudoti šia Sistema, Verslininkas gali pateikti skundą pasinaudodamas skiltimi „Verslininkų skundų pateikimas“ ir pasirinkdamas skundo temą. Verslininkas turi pateikti kaip įmanoma daugiau informacijos apie skundo pagrindą. BALDUGAMYBA.LT atsako Verslininkui patvirtindamas apie gautą skundą ir, dėdamas visas komerciškai pagrįstas pastangas, atsižvelgdamas į skundo kompleksiškumą ir svarbą, kuo greičiau jį išnagrinėja. Išnagrinėjus skundą, atsakymas pateikiamas skundą pateikusiam Verslininkui jo nurodytais kontaktais.</p>
        <p>19.4. Naudodamiesi šia Sistema, Verslininkai gali pateikti skundą:</p>
        <p>19.4.1. kilus įtarimams, kad BALDUGAMYBA.LT nesilaikė Europos Parlamento ir Tarybos Reglamente 2019/1150 nustatytų pareigų, dėl ko buvo pažeisti Verslininko interesai;</p>
        <p>19.4.2. tiesiogiai su Paslaugų teikimu susijusiais techniniais klausimais, kurie daro poveikį Verslininkui;</p>
        <p>19.4.3. dėl priemonių, kurių ėmėsi BALDUGAMYBA.LT, arba BALDUGAMYBA.LT elgesio, tiesiogiai susijusio su Paslaugų teikimu ir darančių poveikį Verslininkui.</p>
        <p>19.5. Privatus klientas prašymą ir (ar) skundą dėl BALDUGAMYBA.LT Svetainės veiklos ir paslaugų pirmiausia raštu privalo pateikti portalui BALDUGAMYBA.LT ir nurodyti savo reikalavimus. Tokius raštus prašome siųsti adresu info@BALDUGAMYBA.LT. Nesutikdamas su BALDUGAMYBA.LT atsakymu, Klientas gali kreiptis į Valstybinę vartotojų teisių apsaugos tarnybą, adresas Vilniaus g. 25, LT-01402 Vilnius, interneto svetainė www.vvtat.lt, ar užpildyti prašymo formą Elektroninėje vartotojų ginčų sprendimo platformoje, adresu http://ec.europa.eu/odr/. Teisminiai ginčai yra nagrinėjami teisės aktų nustatyta tvarka.</p>



        <p>DRAUDŽIAMA DĖTI SKELBIMUS, KURIE SUSIJĘ SU TOLIAU NURODYTŲ OBJEKTŲ PARDAVIMU IR (AR) PIRKIMU:</p>
        <p>akivaizdžiai pornografinio turinio medžiagą arba nuotraukas;</p>
        <p>medžiagą arba nuotraukas kurstančias tautinę, etninę, rasinę, religinę neapykantą, arba neapykantą dėl religijos neišpažinimo;</p>
        <p>trečiųjų asmenų teises, įskaitant teisės į atvaizdą, privatumą, pažeidžiančio turinio medžiagą;</p>
        <p>autorių arba intelektinės nuosavybės teises pažeidžiančius muzikos kūrinius, filmus, programinę įrangą bei kitas prekes;</p>
        <p>pavojingas grynąsias chemines medžiagas, galinčias sukelti pavojų gyvybei, sveikatai arba aplinkai (pvz. sieros rūgštį, karbidą);</p>
        <p>narkotines ir psichotropines medžiagas, ypač narkotikus, taip pat kitas medžiagas naudojamas kaip narkotikų pakaitalai (pakaitines medžiagas), neatsižvelgiant į minėtų medžiagų laikymo ir prekybos jomis teisėtumą;</p>
        <p>su tabako gaminiais susijusius gaminius, įskaitant elektronines cigaretes ir elektroninių cigarečių pildykles, rūkomuosius žolinius gaminius;</p>
        <p>dantų balinimo priemones, kurių sudėtyje yra daugiau nei 0,1% vandenilio peroksido;</p>
        <p>bet kokius vaistus, įskaitant „viagra“, „cialis“ ir kt.;</p>
        <p>maisto papildus, kurie nėra notifikuoti Valstybinės maisto ir veterinarijos tarnybos. Notifikuotų papildų sąrašas pateiktas adresu http://www.vet.lt/maisto-papildai/;</p>
        <p>žmogaus arba gyvūnų organus;</p>
        <p>pajus, akcijas, obligacijas bei kitus vertybinius popierius, skolinius reikalavimus, investicinių fondų vienetus, draudimo polisus ir produktus bei bet kokius kitus investicijų arba piniginio indėlio forma siūlomus finansinius instrumentus, išskyrus išimtinai kolekcinės vertės materialius vertybinius popierius, jei tokiai prekybai pagal teisės aktus yra reikalingas atitinkamas leidimas ar licencija, ir toks leidimas ar licencija nėra gauti ir (ar)ba jei tokio skelbimo paskelbimas prieštarauja teisės aktams reglamentuojantiems finansinių priemonių reklamą;</p>
        <p>programinės įrangos, kuriai suteikta NFR (neskirta parduoti) licencija, bandomąsias, nemokamas, laikinai nemokamas bei pasibaigusio autorinių teisių galiojimo versijas;</p>
        <p>programinę įrangą arba medžiagą, pritaikytą vykdyti teisės aktus arba visuotinai priimtas padorumo normas pažeidžiančią veiklą, įskaitant:</p>
        <p>kompiuterio virusų arba kitų kenksmingų elementų turinčią programinę įrangą;</p>
        <p>programinę įrangą ir įrenginius leidžiančius rinkti su kompiuterio naudotoju susijusią informaciją jam nežinant;</p>
        <p>stalinių ir nešiojamųjų kompiuterių, kietųjų diskų bei kitų atminties laikmenų ir automobilinių radijo imtuvų blokavimui bei slaptažodžių šalinimui skirtą programinę įrangą ir įrenginius, taip pat su blokavimu bei blokavimo šalinimu susijusią informaciją, instrukcijas bei paslaugas;</p>
        <p>programinę įrangą nuskaitančią elektroninio pašto adresus tinklapiuose bei įgalinančią vykdyti masinį pranešimų siuntimą interneto portalų bei momentinių žinučių ir pokalbių internetu naudotojams ir pan., negavus jų sutikimo;</p>
        <p>serijos numerius parduodamus atskirai be originalios programinės įrangos;</p>
        <p>instrukcijas bei tinklapių ir FTP tarnybinių stočių adresus (nuorodas), kuriuose pateikta informacija:</p>
        <p>leidžia arba palengvina pavojingų medžiagų gamybą arba įsigijimą;</p>
        <p>pažeidžia galiojančius teisės aktus arba yra slapta;</p>
        <p>leidžia arba palengvina galiojančių teisės aktų pažeidimą;</p>
        <p>nemokamų interneto portalų paskyras, įskaitant:</p>
        <p>momentinių žinučių ir pokalbių internetu paskyras (pvz. Gadu-Gadu, Tlen, Skype, Jabber, AQQ, ICQ);</p>
        <p>nemokamo elektroninio pašto paskyras (elektroninio pašto adresus);</p>
        <p>nemokamuose interneto portaluose sukurtas paskyras bei kvietimus naudotis šių portalų paslaugomis bei sukurti juose paskyras;</p>
        <p>partnerystės ir lojalumo programų paskyras bei su minėtomis programomis susijusiais paslaugas;</p>
        <p>asmens duomenis arba elektroninio pašto adresų sąrašus;</p>
        <p>išankstinio apmokėjimo korteles;
        <p>paslaugas ir medžiagą, susijusią su dalyvavimu vadinamosiose finansų piramidėse, t.y. naujų narių pritraukimo principu kuriamose finansų struktūrose, kuriose pagrindinis (arba vienintelis) pelno šaltinis yra naujų narių mokamas registravimo mokestis;</p>
        <p>biržos investicijų sistemas, loterijų ir lažybų sistemas bei paslaugas susijusias su dalyvavimu loterijose bei lažybose, išskyrus oficialius knygos formatu išleistus leidinius, kuriems suteiktas ISBN numeris;</p>
        <p>žvejybos įrankius ir įrangą, kurių laikymą riboja teisės aktų nuostatos;</p>
        <p>ginklus ir šaudmenis, kurių laikymui arba prekybai būtina gauti atitinkamą leidimą arba juos registruoti bei dujinius granatsvaidžius ir pipirinių dujų purkštuvus, neatsižvelgiant į minėtų priemonių laikymo ir prekybos jomis teisėtumą, visus A ir B kategorijoms priskiriamus ginklus;</p>
        <p>registracijos liudijimus ir korteles siūlomas atskirai nuo transporto priemonių, kurioms jos išduotos;</p>
        <p>el. pašto paslaugas: t.y. masinio elektroninio susirašinėjimo aptarnavimo paslaugas;</p>
        <p>paslaugas ir medžiagą, skatinančias siųsti papildomai apmokestintas trumpąsias žinutes (vadinamasis „SMS Premium“);</p>
        <p>uždarbį internetu partnerystės sistemose (pvz. darbą spaudinėjant nuorodas);</p>
        <p>fluorintomis šiltnamio efektą sukeliančiomis dujomis užpildytą vienkartinę tarą;</p>
        <p>kitas prekes ir (ar) paslaugas, kurių prekyba yra uždrausta ar ribojama, joms reikalingos atitinkamos licencijos ar leidimai, kurių Klientas neturi, arba tokios licencijos ir leidimai nesuteikia teisės tokias prekes ir (ar) paslaugas parduoti elektroninėmis ryšio priemonėmis, įskaitant internete;</p>
        <p>taip pat bet kokias kitas prekes ir (ar) paslaugas, kai jų prekybą, įskaitant internete, draudžia teisės aktai.</p>
        <p>Pažymėtina, kad šis sąrašas nėra baigtinis, todėl Klientas siūlydamas įsigyti ir (ar) parduoti prekes ir (ar) paslaugas, kai prekyba jomis galimai pažeidžia teisės aktų reikalavimus, veikia išimtinai savo rizika, ir BALDUGAMYBA.LT jokiomis aplinkybėmis nebus atsakinga už tokių Skelbimų Turinį.</p>

    </div>
@endsection
